[libraries]
jetbrains-annotations = "org.jetbrains:annotations:23.0.0"
guava = "com.google.guava:guava:31.0.1-jre"
junit-bom = "org.junit:junit-bom:5.8.2"
junit-jupiter-api.module = "org.junit.jupiter:junit-jupiter-api"
junit-jupiter-engine.module = "org.junit.jupiter:junit-jupiter-engine"
truth = "com.google.truth:truth:1.1.3"
