name: Gradle Build
on: [ push, pull_request ]

jobs:
  build:
    name: Build lin-bus on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build -s
      - name: "Kill Daemons Because Apparently GitHub Won't Do It For You"
        run: ./gradlew --stop
      - uses: actions/upload-artifact@v4
        name: Archive Reports
        if: always()
        with:
          name: reports for ${{ matrix.os }}
          path: '**/build/reports/**'
