name: Gradle Build
on: [ push, pull_request ]

jobs:
  build:
    name: Build lin-bus on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: 'gradle'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew build -s
      - name: "Kill Daemons Because Apparently GitHub Won't Do It For You"
        run: ./gradlew --stop
      - uses: actions/upload-artifact@v3
        name: Archive Reports
        if: always()
        with:
          name: reports for ${{ matrix.os }}
          path: '**/build/reports/**'
  deploy:
    name: Deploy lin-bus to Artifactory
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: 'gradle'
          distribution: 'temurin'
      - name: Deploy to Artifactory
        shell: bash
        env:
          ORG_GRADLE_PROJECT_artifactory_contextUrl: ${{ secrets.ARTIFACTORY_CONTEXTURL }}
          ORG_GRADLE_PROJECT_artifactory_user: ${{ secrets.ARTIFACTORY_USER }}
          ORG_GRADLE_PROJECT_artifactory_password: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: ./gradlew publishToMavenLocal artifactoryPublish -s
